# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontrunning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookCustomerOrder',
            new_name='AppleOrder',
        ),
        migrations.RenameModel(
            old_name='WallmartCustomerOrder',
            new_name='FacebookOrder',
        ),
        migrations.RenameModel(
            old_name='WalmartFirmOrder',
            new_name='WallmartOrder',
        ),
        migrations.DeleteModel(
            name='AppleCustomerOrder',
        ),
        migrations.DeleteModel(
            name='AppleFirmOrder',
        ),
        migrations.DeleteModel(
            name='FacebookFirmOrder',
        ),
    ]
