# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontrunning', '0004_auto_20170830_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
