# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontrunning', '0005_auto_20170830_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleorder',
            name='trade_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facebookorder',
            name='trade_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walmartorder',
            name='trade_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
