# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontrunning', '0006_auto_20170830_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudlist',
            name='security',
            field=models.CharField(default='ápple', max_length=200),
            preserve_default=False,
        ),
    ]
